[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000